### ISSUE TITLE
Ordered List / Copy-Paste does not handled properly

### ISSUE THREAD

**Issue by mhmttosun** [ocavue/prosemirror-flat-list#190]
Hey,

When I paste nested ordered list, all first level items start with 1 insted of 2. 3. ...
You can test it this data https://onecompiler.com/html/3yaecg7bu

https://github.com/ocavue/prosemirror-flat-list/assets/1749183/3dcfadb3-bb9d-43ac-818a-f5cbc7fa951d

Thanks.

**Comment by ocavue** [comment]
The following HTML is invalid. `<ol>` should only contains `<li>` elements.

```html
    <ol>
        <li>Backgroung Skills</li>
        <ol>
            <li>Unix Commands</li>
            <li>Vim Test Editors</li>
        </ol>
        <li>HTML</li>
        <ol>
            <li>minimal page</li>
            <li>Headings</li>
            <li>Elemants</li>
        </ol>
    </ol>
```

To make it valid, you would need to wrap the sub `<ol>` elements within `<li></li>`, like this:

```html
    <ol>
        <li>Backgroung Skills
            <ol>
                <li>Unix Commands</li>
                <li>Vim Test Editors</li>
            </ol>
        </li>
        <li>HTML
            <ol>
                <li>minimal page</li>
                <li>Headings</li>
                <li>Elemants</li>
            </ol>
        </li>
    </ol>
```

Note that these two HTML codes will render the same content in the browser because browsers are quite robust and can handle various invalid HTML codes. However, prosemirror-flat-list currently can only handle the last one (the correct one).

**Comment by ocavue** [comment]
I do not oppose adding some additional code to enable prosemirror-flat-list to support some invalid HTML. PRs are Welcome if anyone wants to improve it.

**Comment by mhmttosun** [comment]
Sorry,
You are wright, I did not realize that it is invalid structure.
