### ISSUE TITLE
Feature Request - Integration of Collapsible Functionality with Ordered, Unordered, and Task Lists

### ISSUE THREAD

**Issue by dwzkit** [ocavue/prosemirror-flat-list#191]
Hello and thank you for developing this plugin, which has significantly enhanced the user experience with intuitive list interactions. I have successfully deployed it in a production environment. I'd like to suggest a feature enhancement that could further improve its functionality.

Currently, the collapsible list feature exists as a separate list type, parallel to ordered lists, unordered lists, and task lists. In our documentation processes, we frequently use lists that often include images, making the list content lengthy. The ability to collapse these lists would be incredibly valuable for managing content length and improving readability.

However, the current implementation of collapsible lists as a separate entity from the other three list types poses a limitation. It would be highly beneficial if there were a way to integrate collapsible functionality with ordered, unordered, and task lists. This integration would allow these lists to maintain their numbering and bullet points while also gaining collapsible capabilities.

I have attached a screenshot to illustrate this concept further. This feature would significantly enhance the utility of the lists in our documentation, providing a more streamlined and efficient user experience.

<img width="988" alt="图片" src="https://github.com/ocavue/prosemirror-flat-list/assets/41875799/e2bbdce1-f6f4-45d0-baa9-26738d90bd15">
<img width="877" alt="图片" src="https://github.com/ocavue/prosemirror-flat-list/assets/41875799/13b86ff9-edb6-4584-a561-f3060d2daefe">
<img width="632" alt="图片" src="https://github.com/ocavue/prosemirror-flat-list/assets/41875799/faf1d25f-292f-47ae-a6cb-a6079a710bb7">
<img width="529" alt="图片" src="https://github.com/ocavue/prosemirror-flat-list/assets/41875799/6a37c470-9894-443a-846b-0df09b9a65e8">

Thank you for considering this request. Your efforts in continually improving this tool are greatly appreciated.

**Comment by ocavue** [comment]
Hey @dwzkit. Thanks for your kind words. I don't plan to change the current behavior as it would be a big breaking change. However, this library with a high degree of flexibility, and you can do that yourself. I added an example in #192 to show how to custom ordered list nodes so that they can be collapsible. You can do the same thing to task list nodes and bullet list nodes. 

Online demo: https://stackblitz.com/github/ocavue/prosemirror-flat-list/tree/master/examples/with-collapsable-ordered-list 



https://github.com/ocavue/prosemirror-flat-list/assets/24715727/410f129f-dd12-4741-a2ef-24d72535c898

**Comment by sherwinyu** [comment]
@ocavue I'm trying to extend your example (of adding the collapsible toggle to numbered lists) to **also add the toggle to unordered (bullet) lists**. However, I'm struggling following the logic of the custom list plugin logic in #192. It looks like the only difference (to get this to render) is in the `getMarkers` option to `listToDom` - but I can't get this to render the marker for the bullet list section. I think it's because of this [line](https://github.com/ocavue/prosemirror-flat-list/blob/55970d345a135a8dcfabeb0a9410944aea70dc52/packages/core/src/schema/to-dom.ts#L48) that causes the markers to be hidden, but I'm not quite sure.

Happy to open this as a separate issue (and do some more investigation myself) if that would be helpful -- thought I'd ask first to see if I'm missing something obvious.

And thanks for the excellent plugin!

**Comment by ocavue** [comment]
> I think it's because of this [line](https://github.com/ocavue/prosemirror-flat-list/blob/55970d345a135a8dcfabeb0a9410944aea70dc52/packages/core/src/schema/to-dom.ts#L48) that causes the markers to be hidden, but I'm not quite sure.

The purpose of this line is hiding extra parent bullet when you have extra indent levels (i.e. put your text cursor inside a bullet list node and press `Tab` multiple times). 


<img width="1065" alt="Image" src="https://github.com/user-attachments/assets/a297d14e-0ff6-4b1a-9142-4efc36c37a7d" />

**Comment by sherwinyu** [comment]
Ah, yes that explains it! Thanks!
