### ISSUE TITLE
Taping a checkbox should not move the cursor

### ISSUE THREAD

**Issue by ocavue** [ocavue/prosemirror-flat-list#89]
On iOS, taping a checkbox will move the cursor. On macOS, clicking a checkbox won't move the cursor. I'm not sure hot to fix it.

**Comment by jpobley** [comment]
I think it might have something to do with the events that are being subscribed to, but I need to keep digging as to _why._ To confirm that suspicion, I put together a [quick branch](https://github.com/jpobley/prosemirror-flat-list/commit/2d4c9276754c0cbc69b4898f5858f6d757b6cfc2) that uses the `change` event instead of the `mousedown` event, and it works fine on my XCode simulator. It's still an issue for the `toggle` list, though.

https://github.com/ocavue/prosemirror-flat-list/assets/2583256/f7c8ecaf-19af-4d88-86b9-cabb449f72a0

**Comment by jpobley** [comment]
Also, apparently just removing `pointer-events: none` works for checkboxes, too:

```diff
diff --git a/packages/core/src/style.css b/packages/core/src/style.css
index 436d46f..71ab954 100644
--- a/packages/core/src/style.css
+++ b/packages/core/src/style.css
@@ -53,7 +53,7 @@
 
       cursor: pointer;
       & * {
-        pointer-events: none;
+        cursor: pointer;
       }
     }
   }

```
